name: Build Switch Homebrew

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile
        shell: bash
        run: |
          make -j$(nproc)

      - name: Upload NRO artifact
        uses: actions/upload-artifact@v4
        with:
          name: gba-emu-switch-nro
          path: '*.nro'
          if-no-files-found: error
